export const projects = [
  {
    name: "Firebase Webstore",
    type: "Fullstack",
    description: "A full-stack e-commerce platform with user authentication, product listings, shopping cart functionality, and secure payment processing.",
    image: "./placeholder.svg",
    stack: [
      { name: "Google Cloud", icon: "./google-cloud.svg" },
      { name: "Firebase", icon: "./firebase.svg" },
      { name: "Firestore", icon: "./firestore.svg" },
      { name: "Cloud Functions", icon: "./cloud-functions.svg" },
      { name: "Stripe", icon: "./stripe.svg" },
    ],
    githubUrl: "#",
    liveUrl: "#",
  },
  {
    name: "Task Management App",
    type: "Fullstack",
    description: "A responsive task management application with drag-and-drop reordering, filtering, and real-time updates, designed for efficient personal and team productivity.",
    image: "./placeholder.svg",
    stack: [
      { name: "React", icon: "./react.svg" },
      { name: "Node.js", icon: "./nodejs.svg" },
      { name: "Express", icon: "./express.svg" },
    ],
    githubUrl: "#",
    liveUrl: "#",
  },
  {
    name: "Weather Dashboard",
    type: "Frontend",
    description: "An interactive weather dashboard displaying real-time weather data, forecasts, and geographical information using the free Weather API from Open-Meteo.",
    image: "./placeholder.svg",
    stack: [
      { name: "Angular", icon: "./angular.svg" },
      { name: "TypeScript", icon: "./typescript.svg" },
      { name: "Bootstrap", icon: "./bootstrap.svg" },
      { name: "JSON", icon: "./json.svg" },
      { name: "API", icon: "./api.svg" },
    ],
    githubUrl: "#",
    liveUrl: "#",
  },
  {
    name: "Connect 4",
    type: "Frontend",
    description: "A classical game of Connect 4 playable vs. other Players or the Computer hosted on Github Pages.",
    image: "./connect4.png",
    stack: [
      { name: "Next.js", icon: "./next.svg" },
      { name: "React", icon: "./react.svg" },
      { name: "TypeScript", icon: "./typescript.svg" },
      { name: "Tailwind CSS", icon: "./tailwind.svg" },
    ],
    githubUrl: "https://github.com/BachiDev/Connect-4",
    liveUrl: "https://bachidev.github.io/Connect-4/",
  },
  {
    name: "Blog Platform",
    type: "Backend",
    description: "A robust blog platform featuring a rich text editor, user comments, and administrative tools for content management, built with a focus on SEO and performance.",
    image: "./placeholder.svg",
    stack: [
      { name: "Python", icon: "./python.svg" },
      { name: "Django", icon: "./django.svg" },
    ],
    githubUrl: "#",
    liveUrl: "#",
  },
  {
    name: "Social Media Clone",
    type: "Fullstack",
    description: "A simplified social media application allowing users to create posts, follow others, and interact through likes and comments, mimicking core social functionalities.",
    image: "./placeholder.svg",
    stack: [
      { name: "Svelte", icon: "./svelte.svg" },
      { name: "GraphQL", icon: "./graphql.svg" },
    ],
    githubUrl: "#",
    liveUrl: "#",
  },
];