export const projects = [
  {
    name: "CRM Demo",
    type: "Fullstack",
    description:
      "A Demo CRM application featuring a RESTful API and a Database designed to showcase modern web development practices with a focus on clean architecture and robust deployment.",
    image: "./crm-demo.png",
    stack: [
      { name: "Angular", icon: "./angular.svg" },
      { name: "Spring Boot", icon: "./spring-boot.svg" },
      { name: "Hibernate", icon: "./hibernate.svg" },
      { name: "Java", icon: "./java.svg" },
      { name: "PostgreSQL", icon: "./postgresql.svg" },
      { name: "Docker", icon: "./docker.svg" },
      { name: "Gradle", icon: "./gradle.svg" },
      { name: "Swagger", icon: "./swagger.svg" },
      { name: "API", icon: "./api.svg" },
    ],
    githubUrl: "https://github.com/BachiDev/crm-demo",
    liveUrl: "https://bachidev.github.io/crm-demo",
  },
  {
    name: "Hand Gesture Control",
    type: "Machine Learning",
    description:
      "Control a user interface using real-time hand gestures captured from your webcam. This project uses machine learning to recognize specific hand poses and translate them into actions like scrolling and toggling content.",
    image: "./handGestureControl.png",
    stack: [
      { name: "Tensorflow", icon: "./tensorflow.svg" },
      { name: "Machine Learning", icon: "./machine-learning.svg" },
      { name: "Next.js", icon: "./next.svg" },
      { name: "React", icon: "./react.svg" },
      { name: "TypeScript", icon: "./typescript.svg" },
      { name: "Tailwind CSS", icon: "./tailwind.svg" },
    ],
    githubUrl: "https://github.com/BachiDev/hand-gesture-control",
    liveUrl: "https://bachidev.github.io/hand-gesture-control/",
  },
  {
    name: "Firebase Webstore",
    type: "Fullstack",
    description:
      "A Demo e-commerce platform with user authentication and secure payment processing through Stripe utilizing Webhooks and Cloud Functions to maintain real-time data synchronization.",
    image: "./webstore.png",
    stack: [
      { name: "Google Cloud", icon: "./google-cloud.svg" },
      { name: "Firebase", icon: "./firebase.svg" },
      { name: "Firestore", icon: "./firestore.svg" },
      { name: "Cloud Functions", icon: "./cloud-functions.svg" },
      { name: "Stripe", icon: "./stripe.svg" },
      { name: "Next.js", icon: "./next.svg" },
      { name: "React", icon: "./react.svg" },
      { name: "TypeScript", icon: "./typescript.svg" },
      { name: "Tailwind CSS", icon: "./tailwind.svg" },
    ],
    githubUrl: "https://github.com/BachiDev/webstore",
    liveUrl: "https://bachidev-webstore.web.app/",
  },
  {
    name: "Weather Dashboard",
    type: "Frontend",
    description:
      "An interactive weather dashboard displaying real-time weather data and forecasts using the free Weather API from Open-Meteo.",
    image: "./weather.png",
    stack: [
      { name: "Next.js", icon: "./next.svg" },
      { name: "React", icon: "./react.svg" },
      { name: "TypeScript", icon: "./typescript.svg" },
      { name: "Tailwind CSS", icon: "./tailwind.svg" },
      { name: "API", icon: "./api.svg" },
      { name: "JSON", icon: "./json.svg" },
    ],
    githubUrl: "https://github.com/BachiDev/weather",
    liveUrl: "https://bachidev.github.io/weather/",
  },
  {
    name: "Connect 4",
    type: "Frontend",
    description:
      "A classical game of Connect 4 playable vs. other Players or the Computer hosted on Github Pages.",
    image: "./connect4.png",
    stack: [
      { name: "Next.js", icon: "./next.svg" },
      { name: "React", icon: "./react.svg" },
      { name: "TypeScript", icon: "./typescript.svg" },
      { name: "Tailwind CSS", icon: "./tailwind.svg" },
    ],
    githubUrl: "https://github.com/BachiDev/Connect-4",
    liveUrl: "https://bachidev.github.io/Connect-4/",
  },
];
